site_name: MeltedForge Documentation
theme:
  name: material
  language: en
  logo: assets/icon.png
  favicon: assets/icon.ico

  font:
    text: 0xProto
    code: 0xProto Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - toc.integrate
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - search.focus

  palette:
    - scheme: slate
      primary: black
      accent: deep-black

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Introduction: index.md
  - Installation: installation.md
  - First app: first-app.md
  - Progress: progress.md
  - About: about.md

copyright: Copyright(c) 2025-2026 CloudCodingSpace
